apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dktest-dktest-poi-map-app-dev
  annotations:
    argocd/app-name: dktest-dktest-poi-map-app-dev
    backstage.io/kubernetes-id: dktest-dktest-poi-map-app-dev
    backstage.io/kubernetes-namespace: dktest
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=dktest-dktest-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/dktest-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/dktest/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/dktest/deployments/dktest-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/dktest-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://dktest-poi-map-app-dktest.apps.summit23blues.6mbu.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "dkerov"
  system: workshop-system-dktest
  consumesApis:
    - gateway-api-dktest
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-dktest
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "dkerov"
